name: Deploy Built Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # so you can push to orphan branch

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Switch to built branch (or create it)
        run: |
          git switch --orphan main-built
          git rm -rf .

      - name: Copy build output
        run: cp -R build/* .

      - name: Commit & push to built
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: update built artifacts"
          git push --force origin main-built
